### ISSUE TITLE
Can't run the app

### ISSUE THREAD

**Issue by smithaitufe** [johnpapa/event-view#27]
Thanks John for this marvelous work.

I followed the instruction for installation of this project.

Then I typed npm start

However, I got this error

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle event-view@0.0.0~prestart: event-view@0.0.0
6 silly lifecycle event-view@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle event-view@0.0.0~start: event-view@0.0.0
8 verbose lifecycle event-view@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle event-view@0.0.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/smith/Documents/Projects/event-view/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
10 verbose lifecycle event-view@0.0.0~start: CWD: /home/smith/Documents/Projects/event-view
11 silly lifecycle event-view@0.0.0~start: Args: [ '-c',
11 silly lifecycle   'npm run tsc && concurrently "npm run tsc:w" "lite-server" ' ]
12 silly lifecycle event-view@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle event-view@0.0.0~start: Failed to exec start script
14 verbose stack Error: event-view@0.0.0 start: `npm run tsc && concurrently "npm run tsc:w" "lite-server" `
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid event-view@0.0.0
16 verbose cwd /home/smith/Documents/Projects/event-view
17 error Linux 4.4.0-59-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error event-view@0.0.0 start: `npm run tsc && concurrently "npm run tsc:w" "lite-server" `
22 error Exit status 1
23 error Failed at the event-view@0.0.0 start script 'npm run tsc && concurrently "npm run tsc:w" "lite-server" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the event-view package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run tsc && concurrently "npm run tsc:w" "lite-server"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs event-view
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls event-view
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
What could be responsible for this error

**Comment by carmolflu** [comment]
replace :     lift<R>(operator: Operator<T, R>): Observable<T>; from Subject.d.ts with  lift<R>(operator: Operator<T, R>): Observable<R>;

**Comment by carmolflu** [comment]
OR replace version of rxjs to 5.5.2 in package.json  and run npm install again (SAFER FIX) . Npm start should work.
